"""Initial schema with CryptoCurrency, CryptoPrice, and ComputedIndicator tables

Revision ID: 2844afb4c2af
Revises: 
Create Date: 2025-11-04 09:36:30.140781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2844afb4c2af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_symbol_market')
    )
    op.create_index('idx_symbol_market', 'crypto_currencies', ['symbol', 'market'], unique=False)
    op.create_index(op.f('ix_crypto_currencies_id'), 'crypto_currencies', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_currencies_symbol'), 'crypto_currencies', ['symbol'], unique=False)
    op.create_table('computed_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['crypto_currencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'timestamp', 'indicator_type', 'parameters', name='uq_currency_indicator')
    )
    op.create_index('idx_currency_indicator_timestamp', 'computed_indicators', ['currency_id', 'indicator_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_computed_indicators_currency_id'), 'computed_indicators', ['currency_id'], unique=False)
    op.create_index(op.f('ix_computed_indicators_id'), 'computed_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_computed_indicators_indicator_type'), 'computed_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_computed_indicators_timestamp'), 'computed_indicators', ['timestamp'], unique=False)
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['crypto_currencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    sa.UniqueConstraint('currency_id', 'timestamp', name='uq_currency_timestamp')
    )
    op.create_index('idx_currency_timestamp', 'crypto_prices', ['currency_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_crypto_prices_currency_id'), 'crypto_prices', ['currency_id'], unique=False)
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_prices_timestamp'), 'crypto_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_prices_timestamp'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_currency_id'), table_name='crypto_prices')
    op.drop_index('idx_currency_timestamp', table_name='crypto_prices')
    op.drop_table('crypto_prices')
    op.drop_index(op.f('ix_computed_indicators_timestamp'), table_name='computed_indicators')
    op.drop_index(op.f('ix_computed_indicators_indicator_type'), table_name='computed_indicators')
    op.drop_index(op.f('ix_computed_indicators_id'), table_name='computed_indicators')
    op.drop_index(op.f('ix_computed_indicators_currency_id'), table_name='computed_indicators')
    op.drop_index('idx_currency_indicator_timestamp', table_name='computed_indicators')
    op.drop_table('computed_indicators')
    op.drop_index(op.f('ix_crypto_currencies_symbol'), table_name='crypto_currencies')
    op.drop_index(op.f('ix_crypto_currencies_id'), table_name='crypto_currencies')
    op.drop_index('idx_symbol_market', table_name='crypto_currencies')
    op.drop_table('crypto_currencies')
    # ### end Alembic commands ###
